blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/dele-to/dele-to/discussions
    about: Ask questions, share ideas, and get help in Discussions.
